### ISSUE TITLE
Creating some common components

### ISSUE THREAD

**Issue by up2dul** [up2dul/site#3]
Finishing up to create the following components:
- [x] Skip to content - #9 
- [x] Header
- [x] Theme toggler button - #4 
- [x] Footer - #2 
- [x] Writing list card - #10
